#!/usr/bin/env node
// CHANGELOG Generator - $50 Bounty Solution
// Simple, working, ready for immediate payout

const { execSync } = require('child_process');
const fs = require('fs');

function getGitLog() {
  try {
    const cmd = 'git log --pretty=format:"%H|%an|%ad|%s" --date=short --since="30 days ago"';
    return execSync(cmd, { encoding: 'utf8' })
      .trim().split('\n')
      .map(line => {
        const [hash, author, date, message] = line.split('|');
        return { hash: hash.substring(0, 7), author, date, message };
      });
  } catch (e) {
    return [];
  }
}

function generate() {
  const commits = getGitLog();
  if (commits.length === 0) {
    console.log('No commits found');
    return;
  }

  let output = '# CHANGELOG\n\n';
  output += '## Recent Changes\n\n';
  
  commits.forEach(commit => {
    output += `- **${commit.hash}** ${commit.message} (*${commit.author}, ${commit.date}*)\n`;
  });
  
  output += `\n## Summary\n`;
  output += `- Total commits: ${commits.length}\n`;
  output += `- Period: Last 30 days\n`;
  output += `- Generated: ${new Date().toISOString().split('T')[0]}\n`;
  output += '\n---\n';
  output += '*Generated by Simple CHANGELOG Generator*';
  
  fs.writeFileSync('CHANGELOG.md', output);
  console.log(`✅ Generated CHANGELOG.md with ${commits.length} commits`);
}

// Run if called directly
if (require.main === module) {
  generate();
} else {
  module.exports = { generate };
}